apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despachos
  namespace: tienda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-despachos
  template:
    metadata:
      labels:
        app: backend-despachos
      annotations:
        cloudwatch.aws.amazon.com/auto-annotate-java: "false"
        cloudwatch.aws.amazon.com/auto-annotate-nodejs: "false"
        cloudwatch.aws.amazon.com/auto-annotate-python: "false"
        cloudwatch.aws.amazon.com/auto-annotate-dotnet: "false"
        instrumentation.opentelemetry.io/inject-java: "false"
        instrumentation.opentelemetry.io/inject-nodejs: "false"
        instrumentation.opentelemetry.io/inject-python: "false"
        instrumentation.opentelemetry.io/inject-dotnet: "false"
    spec:
      containers:
        - name: backend-despachos
          image: 739067091251.dkr.ecr.us-east-1.amazonaws.com/backend_despachos:eks-v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          startupProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 18
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
